abstract class Position {
    private int x, y;

    protected Position(int x, int y) {
        this.x = x;
        this.y = y;
    }

    // getters and setters generated by IntelliJ
    public int getX() {
        return x;
    }

    public void setX(int x) {
        this.x = x;
    }

    public int getY() {
        return y;
    }

    public void setY(int y) {
        this.y = y;
    }
}
